### ISSUE TITLE
Plugin configuration resets to default after Jellyfin server restart

### ISSUE THREAD

**Issue by balgerion** [KeksBombe/jellyfin-plugin-auto-collections#14]
Restarting the Jellyfin server causes my plugin configuration to be overwritten and replaced with the default one. Is there a way to configure a file so that my custom settings are automatically applied, without having to manually restore them from a JSON file each time?

![Image](https://github.com/user-attachments/assets/7a1922cd-8ce5-473e-8e29-12cba1a0b788)

**Comment by KeksBombe** [comment]
Hi, i cannot reproduce this error... I restarted my server multiple times and my configuration is persistant. The Config gets written into the jellyfin storage when you press save. If you look into the folder in <JellfinRootDirectory>/config/plugins/configurations. There should be a Jellyfin.Plugin.AutoCollections.xml. In there your configuration is saved.

**Comment by balgerion** [comment]
Before restart

![Image](https://github.com/user-attachments/assets/4af4472b-907c-42d2-9a40-692393b8284c)

After

![Image](https://github.com/user-attachments/assets/c4e106af-b8a4-43ce-80aa-1306edc41617)

Hmm, some black magic is happening here. :)

**Comment by ProtoBn7** [comment]
Got exactly the same issue, I set the plugin to have only a collection for eng language shows with the tag "anime".
got the XML file that match my request, and after the restart of Jellifin, the XML file is back to the default one.

**Comment by MattFryer** [comment]
Are you running Jellyfin as a container by any chance? I'm wondering if the location of the config file is not mapped to a persistent volume and so is lost when the contain is restarted.

**Comment by ProtoBn7** [comment]
> Are you running Jellyfin as a container by any chance? I'm wondering if the location of the config file is not mapped to a persistent volume and so is lost when the contain is restarted.

Do you know how I can check that and what to do if that's the case ?

**Comment by balgerion** [comment]
in my case I'm using docker 

docker-compose:

```
 jellyfin:
    image: linuxserver/jellyfin:latest
    container_name: arr-suite-jellyfin
    environment:
      - PUID=1001
      - PGID=988
      - TZ=Europe/Warsaw
    volumes:
      - /mnt/Balgeriada1/docker/app/arr-suite/configs/jellyfin:/config # location of database and configs; can grow very large
      - /mnt/Balgeriada1/Media:/data # location of media library
    expose:
      - 8096/tcp # http web ui
    ports:
      - 8096:8096/tcp # http web ui
    devices:
      - /dev/dri:/dev/dri #optional
    restart: unless-stopped
```
